"""
Signal Engine — Enhanced Triple Confirmation system.

Evaluates all confirmations and generates trade signals
when criteria are met. Now includes:
  - Confluence scoring (Fibonacci, horizontal, VPOC, round numbers)
  - Derivatives context (funding rate, OI)
  - Pump-specific validation
  - Weighted composite scoring
"""

import pandas as pd
import numpy as np
import logging
from dataclasses import dataclass, field

from src.config import (
    MIN_CONFIRMATIONS, RSI_PERIOD, RSI_OVERBOUGHT, RSI_OVERSOLD,
    ATR_PERIOD, STOP_ATR_MULT, TP1_R, TP2_R, TP3_R,
    TP1_PCT, TP2_PCT, TP3_PCT,
    VOLUME_SURGE_MULT, EMA_FAST, EMA_MEDIUM, EMA_SLOW, EMA_GLOBAL,
    TOUCH_ZONE_PCT, RISK_PER_TRADE_PCT,
    COUNTER_TREND_SIZE_MULT, PUMP_SIZE_MULT, NEW_LISTING_SIZE_MULT,
    RECOMMENDED_LEVERAGE, BLOCK_FULL_COUNTER_TREND, MIN_SIGNAL_SCORE,
    MOMENTUM_RSI_EXHAUSTION_LONG, MOMENTUM_RSI_EXHAUSTION_SHORT,
    MOMENTUM_RSI_PENALTY, MOMENTUM_VOLUME_FADE_PENALTY,
    TOTAL_COST_PER_SIDE, BTC_TREND_PENALTY,
)
from src.diagonal_levels import DiagonalLevel, is_price_near_level
from src.candle_patterns import detect_patterns, get_best_pattern
from src.indicators import detect_rsi_divergence, get_trend_direction
from src.confluence import analyze_confluence, ConfluenceResult
from src.derivatives_filter import analyze_derivatives, DerivativesContext
from src.pump_trading import detect_pump, PumpAnalysis

logger = logging.getLogger(__name__)


@dataclass
class Signal:
    """A trade signal generated by the DLS strategy."""
    symbol: str
    direction: str                     # "LONG" or "SHORT"
    scenario: str                      # "uptrend", "downtrend", "pump", "new_listing"
    entry_price: float = 0.0            # Actual market price at signal time
    stop_loss: float = 0.0
    tp1: float = 0.0
    tp2: float = 0.0
    tp3: float = 0.0
    risk_pct: float = 0.0             # Stop distance %
    rr_ratio: float = 0.0            # Weighted avg R:R across TPs (gross)
    rr_net: float = 0.0              # R:R after commissions + slippage
    commission_r: float = 0.0        # Round-trip trading cost in R
    leverage: int = RECOMMENDED_LEVERAGE
    size_multiplier: float = 1.0      # 1.0 = full, 0.75 = pump, 0.5 = counter
    confirmations: dict = field(default_factory=dict)
    num_confirmations: int = 0
    level_strength: float = 0.0
    level_touches: int = 0
    level_angle: float = 0.0
    candle_pattern: str = ""
    rsi_value: float = 0.0
    volume_ratio: float = 0.0
    trend_4h: str = ""
    trend_1h: str = ""
    trend_15m: str = ""
    btc_trend: str = ""               # BTC 4H trend direction
    timestamp: str = ""
    level_price: float = 0.0             # Diagonal level price (reference)
    # Enhanced fields
    composite_score: float = 0.0      # Weighted overall score (0-100)
    confluence: ConfluenceResult = field(default_factory=ConfluenceResult)
    derivatives: DerivativesContext = field(default_factory=DerivativesContext)
    pump_analysis: PumpAnalysis = field(default_factory=PumpAnalysis)
    signal_grade: str = ""            # "A+", "A", "B", "C"


def _compute_composite_score(
    num_confirmations: int,
    level_strength: float,
    confluence_score: float,
    derivatives_adj: float,
    regime_adj: float,
) -> float:
    """
    Compute weighted composite score for the signal.

    Components:
      - Confirmations: 30% weight (3/5=60, 4/5=80, 5/5=100)
      - Level strength: 25% weight (0-100 from diagonal level detector)
      - Confluence: 25% weight (0-100 from confluence analyzer)
      - Derivatives: 10% weight (adjustment from funding/OI)
      - Market regime: 10% weight (session, volatility)

    Returns 0-100 composite score.
    """
    conf_score = min(num_confirmations / 5.0 * 100, 100) * 0.30
    level_score = min(level_strength, 100) * 0.25
    confl_score = min(confluence_score, 100) * 0.25
    deriv_score = max(0, min(50 + derivatives_adj, 100)) * 0.10
    regime_score = max(0, min(50 + regime_adj, 100)) * 0.10

    total = conf_score + level_score + confl_score + deriv_score + regime_score
    return min(round(total, 1), 100)


def _grade_signal(score: float) -> str:
    """Assign a letter grade based on composite score."""
    if score >= 80:
        return "A+"
    elif score >= 65:
        return "A"
    elif score >= 50:
        return "B"
    elif score >= 35:
        return "C"
    return "D"


def evaluate_signal(
    symbol: str,
    scenario: str,
    level: DiagonalLevel,
    df_working: pd.DataFrame,
    df_entry: pd.DataFrame,
    trend_4h: str,
    trend_1h: str,
    timeframe: str = "15m",
    funding_rate: float | None = None,
    open_interest: float | None = None,
    regime_adjustment: float = 0.0,
    btc_trend_4h: str = "neutral",
) -> Signal | None:
    """
    Evaluate all confirmations for a potential signal.

    Returns Signal if 3+ confirmations met, else None.
    Now includes confluence analysis, derivatives context, and composite scoring.
    """
    if df_working is None or len(df_working) < 20:
        return None
    if df_entry is None or len(df_entry) < 5:
        return None

    last_w = df_working.iloc[-1]
    current_price = float(last_w["close"])
    candle_idx = len(df_working) - 1

    # Determine trade direction based on level type
    if level.level_type == "support":
        direction = "LONG"
    else:
        direction = "SHORT"

    # For pump scenario, SHORT on deflation from resistance
    if scenario == "pump" and level.level_type == "resistance":
        direction = "SHORT"

    confirmations = {}

    # ── CONFIRMATION 1: Diagonal Level Touch (mandatory) ─────
    # Check last 3 candles for proximity to level (not just the last one)
    near_level = False
    best_candle_idx = candle_idx
    for lookback in range(3):
        idx = candle_idx - lookback
        if idx < 0:
            break
        check_price = float(df_working.iloc[idx]["close"])
        if is_price_near_level(check_price, level, idx, timeframe):
            near_level = True
            best_candle_idx = idx
            break
        # Also check high/low wicks
        check_high = float(df_working.iloc[idx]["high"])
        check_low = float(df_working.iloc[idx]["low"])
        if level.level_type == "support":
            if is_price_near_level(check_low, level, idx, timeframe):
                near_level = True
                best_candle_idx = idx
                break
        else:
            if is_price_near_level(check_high, level, idx, timeframe):
                near_level = True
                best_candle_idx = idx
                break

    confirmations["diagonal_level"] = near_level

    if not near_level:
        # Diagnostic logging: show distance to level
        level_price = level.price_at(candle_idx)
        if level_price > 0:
            distance_pct = abs(current_price - level_price) / level_price * 100
            if distance_pct < 2.0:  # Only log if relatively close
                logger.debug(
                    f"    {symbol}: {level.level_type} уровень — цена {current_price:.4f}, "
                    f"уровень {level_price:.4f}, расстояние {distance_pct:.2f}%"
                )
        return None

    # ── CONFIRMATION 2: Candle Pattern ───────────────────────
    patterns = detect_patterns(df_entry)
    desired_dir = "bullish" if direction == "LONG" else "bearish"
    best_pattern = get_best_pattern(patterns, desired_dir)
    confirmations["candle_pattern"] = best_pattern is not None

    # ── CONFIRMATION 3: Volume ───────────────────────────────
    # Check last 3 candles for volume surge (not just the last one)
    vol_ratio = 0.0
    for lookback in range(3):
        idx = candle_idx - lookback
        if idx < 0:
            break
        vr = float(df_working.iloc[idx].get("volume_ratio", 0))
        vol_ratio = max(vol_ratio, vr)
    confirmations["volume"] = vol_ratio >= VOLUME_SURGE_MULT

    # ── CONFIRMATION 4: Indicator (RSI + MACD + Divergence) ──
    rsi = float(last_w.get(f"RSI_{RSI_PERIOD}", 50))
    macd_hist_col = [c for c in df_working.columns if "MACDh" in c or "MACD_hist" in c.lower()]
    macd_hist = 0
    if macd_hist_col:
        macd_hist = float(last_w.get(macd_hist_col[0], 0))

    indicator_ok = False
    if direction == "LONG":
        indicator_ok = (rsi < 50 or macd_hist > 0)
        div = detect_rsi_divergence(df_working)
        if div == "bullish":
            indicator_ok = True
    else:
        indicator_ok = (rsi > 50 or macd_hist < 0)
        div = detect_rsi_divergence(df_working)
        if div == "bearish":
            indicator_ok = True

    confirmations["indicator"] = indicator_ok

    # ── CONFIRMATION 5: Confluence (enhanced) ────────────────
    level_price = level.price_at(best_candle_idx)
    confluence = analyze_confluence(level_price, df_working, df_working)
    confirmations["confluence"] = confluence.score >= 15  # Lowered from 20

    # ── Count confirmations ──────────────────────────────────
    num_conf = sum(1 for v in confirmations.values() if v)

    # Diagnostic logging: always log when price is near level
    conf_str = " | ".join(
        f"{k}={'OK' if v else 'FAIL'}" for k, v in confirmations.items()
    )
    logger.info(
        f"    {symbol}: ОКОЛО УРОВНЯ ({level.level_type}) — "
        f"конф. {num_conf}/{MIN_CONFIRMATIONS} нужно [{conf_str}]"
    )

    if num_conf < MIN_CONFIRMATIONS:
        return None

    # ── Derivatives context check ────────────────────────────
    deriv_ctx = analyze_derivatives(funding_rate, open_interest, direction)

    # Kill switch: extreme funding blocks all trades
    if deriv_ctx.is_extreme:
        logger.info(f"  {symbol}: blocked by derivatives kill switch — {deriv_ctx.reason}")
        return None

    # ── Pump validation (if pump scenario) ───────────────────
    pump = PumpAnalysis()
    if scenario == "pump":
        pump = detect_pump(df_working, timeframe)
        if pump.is_pump and not pump.is_tradeable:
            logger.info(f"  {symbol}: pump not tradeable — {pump.reason}")
            return None

    # ── Compute entry, stop, targets ─────────────────────────
    atr = float(last_w.get(f"ATR_{ATR_PERIOD}", 0))
    if atr <= 0:
        return None

    zone_pct = TOUCH_ZONE_PCT.get(timeframe, 0.0015)

    # Entry = current market price (not level price — user enters at market)
    # Stop = level-based (placed beyond the support/resistance)
    # TPs = calculated from actual entry with real stop distance
    entry_price = current_price

    if direction == "LONG":
        stop_loss = level_price * (1 - zone_pct) - atr * STOP_ATR_MULT
        stop_dist = entry_price - stop_loss
        if stop_dist <= 0:
            return None
        tp1 = entry_price + stop_dist * TP1_R
        tp2 = entry_price + stop_dist * TP2_R
        tp3 = entry_price + stop_dist * TP3_R
    else:
        stop_loss = level_price * (1 + zone_pct) + atr * STOP_ATR_MULT
        stop_dist = stop_loss - entry_price
        if stop_dist <= 0:
            return None
        tp1 = entry_price - stop_dist * TP1_R
        tp2 = entry_price - stop_dist * TP2_R
        tp3 = entry_price - stop_dist * TP3_R

    risk_pct = stop_dist / entry_price if entry_price > 0 else 0

    # Real R:R based on weighted average TP
    weighted_tp_r = TP1_R * TP1_PCT + TP2_R * TP2_PCT + TP3_R * TP3_PCT
    rr_ratio = round(weighted_tp_r, 1)

    # Net R:R after commissions + slippage
    commission_r = round(2 * TOTAL_COST_PER_SIDE / risk_pct, 2) if risk_pct > 0 else 0
    rr_net = round(weighted_tp_r - commission_r, 1)

    # ── Counter-trend check ────────────────────────────────
    trend_15m = get_trend_direction(df_working)
    is_counter_trend = (
        (direction == "LONG" and trend_1h == "bearish") or
        (direction == "SHORT" and trend_1h == "bullish")
    )

    # Block signal when ALL timeframes agree against the direction
    if BLOCK_FULL_COUNTER_TREND and is_counter_trend:
        all_against = (
            (direction == "LONG" and trend_4h == "bearish"
             and trend_1h == "bearish" and trend_15m == "bearish") or
            (direction == "SHORT" and trend_4h == "bullish"
             and trend_1h == "bullish" and trend_15m == "bullish")
        )
        if all_against:
            logger.info(
                f"  {symbol}: блок полного контр-тренда — "
                f"{direction} при 4H={trend_4h} 1H={trend_1h} 15m={trend_15m}"
            )
            return None

    size_mult = 1.0
    if is_counter_trend:
        size_mult = COUNTER_TREND_SIZE_MULT
    elif scenario == "pump":
        size_mult = PUMP_SIZE_MULT
    elif scenario == "new_listing":
        size_mult = NEW_LISTING_SIZE_MULT

    # ── Momentum freshness check ──────────────────────────────
    # Penalize signals where the move may already be exhausted
    momentum_penalty = 0.0

    # 1. RSI exhaustion: entering SHORT when already oversold (or LONG when overbought)
    if direction == "LONG" and rsi > MOMENTUM_RSI_EXHAUSTION_LONG:
        momentum_penalty += MOMENTUM_RSI_PENALTY
        logger.info(
            f"  {symbol}: RSI exhaustion (LONG при RSI={rsi:.1f} > {MOMENTUM_RSI_EXHAUSTION_LONG}) "
            f"— штраф -{MOMENTUM_RSI_PENALTY}"
        )
    elif direction == "SHORT" and rsi < MOMENTUM_RSI_EXHAUSTION_SHORT:
        momentum_penalty += MOMENTUM_RSI_PENALTY
        logger.info(
            f"  {symbol}: RSI exhaustion (SHORT при RSI={rsi:.1f} < {MOMENTUM_RSI_EXHAUSTION_SHORT}) "
            f"— штраф -{MOMENTUM_RSI_PENALTY}"
        )

    # 2. Volume freshness: surge was earlier but current candle volume is below average
    current_vol_ratio = float(df_working.iloc[-1].get("volume_ratio", 0))
    if vol_ratio >= VOLUME_SURGE_MULT and current_vol_ratio < 1.0:
        momentum_penalty += MOMENTUM_VOLUME_FADE_PENALTY
        logger.info(
            f"  {symbol}: Volume fading (всплеск={vol_ratio:.2f}x, "
            f"текущий={current_vol_ratio:.2f}x) — штраф -{MOMENTUM_VOLUME_FADE_PENALTY}"
        )

    # ── BTC directional filter ─────────────────────────────────
    btc_penalty = 0.0
    btc_counter = False
    if btc_trend_4h == "bearish" and direction == "LONG":
        btc_penalty = BTC_TREND_PENALTY
        btc_counter = True
        logger.info(
            f"  {symbol}: BTC 4H bearish vs LONG — штраф -{BTC_TREND_PENALTY}"
        )
    elif btc_trend_4h == "bullish" and direction == "SHORT":
        btc_penalty = BTC_TREND_PENALTY
        btc_counter = True
        logger.info(
            f"  {symbol}: BTC 4H bullish vs SHORT — штраф -{BTC_TREND_PENALTY}"
        )

    # ── Composite score ──────────────────────────────────────
    composite = _compute_composite_score(
        num_confirmations=num_conf,
        level_strength=level.strength,
        confluence_score=confluence.score,
        derivatives_adj=deriv_ctx.score_adjustment,
        regime_adj=regime_adjustment,
    )
    # Apply momentum + BTC penalties
    composite = max(0, composite - momentum_penalty - btc_penalty)
    grade = _grade_signal(composite)

    # ── Minimum score filter ─────────────────────────────────
    if composite < MIN_SIGNAL_SCORE:
        logger.info(
            f"  {symbol}: скор {composite:.0f} < {MIN_SIGNAL_SCORE} ({grade}) — пропущен"
        )
        return None

    # ── Build signal ─────────────────────────────────────────
    signal = Signal(
        symbol=symbol,
        direction=direction,
        scenario=scenario,
        entry_price=round(entry_price, 6),
        stop_loss=round(stop_loss, 6),
        tp1=round(tp1, 6),
        tp2=round(tp2, 6),
        tp3=round(tp3, 6),
        risk_pct=round(risk_pct, 5),
        rr_ratio=rr_ratio,
        rr_net=rr_net,
        commission_r=commission_r,
        leverage=RECOMMENDED_LEVERAGE,
        size_multiplier=size_mult,
        confirmations=confirmations,
        num_confirmations=num_conf,
        level_strength=level.strength,
        level_touches=level.num_touches,
        level_angle=round(level.angle_deg, 1),
        candle_pattern=best_pattern["pattern"] if best_pattern else "",
        rsi_value=round(rsi, 1),
        volume_ratio=round(vol_ratio, 2),
        trend_4h=trend_4h,
        trend_1h=trend_1h,
        trend_15m=trend_15m,
        btc_trend=btc_trend_4h,
        timestamp=str(last_w.name) if hasattr(last_w, "name") else "",
        level_price=round(level_price, 6),
        composite_score=composite,
        confluence=confluence,
        derivatives=deriv_ctx,
        pump_analysis=pump,
        signal_grade=grade,
    )

    return signal
